#!/usr/bin/env python3
"""Copy original assets/catalogs deterministically; never modify iOS resources."""
from pathlib import Path
import json
import re
import shutil

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "android/app/src/main"
# Only platform substitutions and compositional labels absent from the iOS catalog.
ADDITIONS = {
    "%lld 小时": ["%lld 小時", "%lld hours", "%lld 時間", "%lld시간"],
    "API key 使用 Android Keystore 加密保存在本机": ["API key 使用 Android Keystore 加密儲存在本機", "API keys are encrypted locally using Android Keystore", "API key は Android Keystore で暗号化して端末に保存", "API key는 Android Keystore로 암호화하여 기기에 저장됩니다"],
    "RPC 请求失败": ["RPC 請求失敗", "RPC request failed", "RPC リクエストに失敗しました", "RPC 요청 실패"],
    "上移": ["上移", "Move up", "上へ移動", "위로 이동"],
    "下移": ["下移", "Move down", "下へ移動", "아래로 이동"],
    "主题": ["主題", "Theme", "テーマ", "테마"],
    "仅删除本机连接及凭据，不删除服务器。": ["僅刪除本機連線及憑據，不刪除伺服器。", "Remove only the local connection and credentials. The server is not deleted.", "この端末の接続と認証情報のみ削除します。サーバーは削除されません。", "기기의 연결과 인증 정보만 삭제합니다. 서버는 삭제되지 않습니다."],
    "已选择": ["已選取", "Selected", "選択済み", "선택됨"],
    "执行状态可能不确定，请刷新任务列表核对；不会自动重试。": ["執行狀態可能不確定，請重新整理任務清單核對；不會自動重試。", "Execution status may be uncertain. Refresh the task list to verify; this request will not retry automatically.", "実行状態が不明な可能性があります。タスク一覧を更新して確認してください。自動再試行はしません。", "실행 상태가 불확실할 수 있습니다. 작업 목록을 새로 고쳐 확인하세요. 자동 재시도하지 않습니다."],
    "服务器返回 HTTP 错误。": ["伺服器傳回 HTTP 錯誤。", "The server returned an HTTP error.", "サーバーが HTTP エラーを返しました。", "서버에서 HTTP 오류를 반환했습니다."],
    "返回": ["返回", "Back", "戻る", "뒤로"],
    "配置已被其他人修改，请关闭并重新编辑。": ["設定已被其他人修改，請關閉並重新編輯。", "This configuration was modified elsewhere. Close and edit it again.", "設定が別の場所で変更されました。閉じてから再編集してください。", "다른 곳에서 설정이 변경되었습니다. 닫은 후 다시 편집하세요."],
    "隐藏的节点仅影响本机显示。": ["隱藏節點僅影響本機顯示。", "Hiding nodes only affects this device's display.", "ノードの非表示はこの端末の表示にのみ影響します。", "노드 숨김은 이 기기의 표시에만 영향을 줍니다."],
    "iOS 原项目": ["iOS 原始專案", "Original iOS project", "元の iOS プロジェクト", "원본 iOS 프로젝트"],
}


def main():
    assets = OUT / "assets"
    assets.mkdir(parents=True, exist_ok=True)
    catalogs = {}
    for source in sorted((ROOT / "KomariPanel").glob("*.lproj/Localizable.strings")):
        pairs = re.findall(r'("(?:\\.|[^"\\])*")\s*=\s*("(?:\\.|[^"\\])*")\s*;', source.read_text())
        catalogs[source.parent.stem] = {json.loads(k): json.loads(v) for k, v in pairs}
    for key, values in ADDITIONS.items():
        catalogs["zh-Hans"][key] = key
        for language, translation in zip(["zh-Hant", "en", "ja", "ko"], values):
            catalogs[language][key] = translation
    (assets / "i18n.json").write_text(json.dumps(catalogs, ensure_ascii=False, sort_keys=True, indent=2) + "\n")
    images = OUT / "res/drawable-nodpi"
    images.mkdir(parents=True, exist_ok=True)
    for source in sorted((ROOT / "KomariPanel/Assets.xcassets").glob("*.imageset/icon.png")):
        shutil.copyfile(source, images / (source.parent.stem.lower().replace("-", "_") + ".png"))
    icon = ROOT / "KomariPanel/Assets.xcassets/AppIcon.appiconset"
    manifest = json.loads((icon / "Contents.json").read_text())
    shutil.copyfile(icon / next(i["filename"] for i in manifest["images"] if not i.get("appearances")), images / "app_icon.png")
    # Static references let Android verify/retain every offline identity resource.
    resource_map = ["package com.khixang.panel.android", "", "// Generated by scripts/sync-ios-resources.py", "object IdentityResources {"]
    for field, prefix in [("flags", "flag_"), ("operatingSystems", "os_")]:
        resource_map.append(f"    val {field}: Map<String,Int> = mapOf(")
        for image in sorted(images.glob(prefix + "*.png")):
            key = image.stem.removeprefix(prefix).upper().replace("_", "-") if prefix == "flag_" else image.stem
            resource_map.append(f'        "{key}" to R.drawable.{image.stem},')
        resource_map.append("    )")
    resource_map.append("}")
    (OUT / "java/com/khixang/panel/android/IdentityResources.kt").write_text("\n".join(resource_map) + "\n")
    notices = (ROOT / "KomariPanel/ThirdPartyNotices.txt").read_text()
    notices += "\n\nAndroid port runtime libraries: AndroidX / Jetpack Compose, Kotlin, kotlinx.coroutines, kotlinx.serialization and OkHttp (Apache License 2.0).\nhttps://www.apache.org/licenses/LICENSE-2.0\nOriginal iOS project: https://github.com/Likhixang/Monitor-Panel-iOS\n"
    (assets / "ThirdPartyNotices.txt").write_text(notices)
    source = (ROOT / "KomariPanel/NodeIdentity.swift").read_text().split("static let alpha3ToAlpha2")[1]
    countries = dict(re.findall(r'"([A-Z]{3})": "([A-Z]{2})"', source))
    (assets / "country-codes.json").write_text(json.dumps(countries, sort_keys=True) + "\n")
    print(f"Synced {len(list(images.glob('*.png')))} images and {len(catalogs)} catalogs.")


if __name__ == "__main__":
    main()
